apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-app
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
    argocd.argoproj.io/manifest-generate-paths: /helm/hello
spec:
  project: default
  source:  
    repoURL: https://github.com/rdiazgav/test-gitops.git
    targetRevision: main
    path: helm/hello
    source:
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: hello-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
