apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-app-multirepo
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  project: default
  sources:  
  - repoURL: https://github.com/rdiazgav/test-gitops-helm.git
    targetRevision: main
    path: helm/hello    
    helm:
      valueFiles:
        - $values/application/values/values-multi.yaml
  - ref: values
    repoURL: https://github.com/rdiazgav/test-gitops.git
    targetRevision: 'main'
  destination:
    server: https://kubernetes.default.svc
    namespace: hello-gitops-multirepo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
