apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: hello-appset
  namespace: openshift-gitops
spec:
  generators:    
    - git:
        repoURL: 'https://github.com/rdiazgav/test-gitops.git'
        revision: main
        files:
          - path: '/application/envs/*.yaml'
  template:
    metadata:     
      annotations:
        argocd.argoproj.io/manifest-generate-paths: '{{values_dir}};/helm/hello'
      name: 'hello-appset-{{env}}'
    spec:
      project: default
      source:
        path: helm/hello
        repoURL: 'https://github.com/rdiazgav/test-gitops.git'
        targetRevision: main
        helm:
          valueFiles:
            - '{{values_dir}}'
      destination:
        namespace: 'hello-gitops-{{env}}'
        server: 'https://kubernetes.default.svc'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        managedNamespaceMetadata:
          labels:
            argocd.argoproj.io/managed-by: openshift-gitops
        syncOptions:
          - CreateNamespace=true
